{
 "title": "Axa ddc alertings",
 "tags": [ "axaddc" ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "[RCE Ecran] Error 500",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\n    increase(http_server_request_duration_count{http_response_status_code=~\"5..\", exported_job=\"rce-axaddc-ecrans\"}[5m])\n  )"
    }
   ]
  },
  {
   "title": "[RCE Ecran] Time per requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(opentelemetry_spanmetrics_latency_bucket{service_name=~\"rce-axaddc-ecrans\"}[5m])) by (operation, le)) >0"
    }
   ]
  },
  {
   "title": "[RCE API] Time per requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(opentelemetry_spanmetrics_latency_bucket{service_name=~\"rce-axaddc-api\", operation!=\"POST api/v{version:apiVersion}/Conformity/LifeControl\"}[5m])) by (operation, le)) >0"
    }
   ]
  },
  {
   "title": "[RCE API] Exceptions",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(process_runtime_dotnet_exceptions_count{exported_job=\"rce-axaddc-api\"}[5m])",
     "legendFormat": " {{exported_instance}}"
    }
   ]
  },
  {
   "title": "[RCE Ecrans] Exceptions",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(process_runtime_dotnet_exceptions_count{exported_job=\"rce-axaddc-ecrans\"}[5m])",
     "legendFormat": " {{exported_instance}}"
    }
   ]
  }
 ]
}